from enum import Enum

class ChargerStatus(Enum):
    CHARGER_AVAILABLE = "AVAILABLE"
    CHARGER_BUSY = "BUSY"
    CHARGER_NOT_WORKING = "FAULTY"
    CHARGER_BOOKED = "BOOKED"
    CHARGER_RESERVED = "RESERVED"


class ChargingStatus(Enum):
    BOOKED = 'BOOKED'
    STARTED = 'STARTED'
    START_FAILED = "START_FAILED"
    IN_PROGRESS = 'IN_PROGRESS'
    PROGRESS_UPDATE_UNKNOWN = 'PROGRESS_UPDATE_UNKNOWN'
    USER_STOPPED = 'USER_STOPPED'
    COMPLETED = 'COMPLETED'
    TERMINATED = 'TERMINATED'
    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
    STOP_FAILED = 'STOP_FAILED'

